### ISSUE TITLE
go-blip keepalive questions

### ISSUE THREAD

**Issue by tleyden** [couchbase/go-blip#12]
If go-blip is used as a client, will it need to set a [TCP keepalive](http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html) value to prevent load balancers or other network middleware from closing the connection?

Also, somewhat related, will Sync Gateway acting as a passive blip replicator ever need the equivalent of the HTTP continuous _changes feed heartbeat mechanism to prevent sockets from being closed by load balancers?   Any pointers on the history of the impetus behind this heartbeat mechanism would be useful -- I'm curious why TCP keepalive isn't good enough?  Is it because of certain load balancers that ignore TCP keepalive settings?  Or to centralize the functionality in Sync Gateway rather than having to setup TCP keepalive on all CBLite clients?

**Comment by tleyden** [comment]
> Any pointers on the history of the impetus behind this heartbeat mechanism would be useful

I think I've managed to trace back to the original ticket where the SG heartbeat was added:

https://github.com/couchbase/sync_gateway/issues/164

which references:

https://github.com/couchbase/couchbase-lite-ios/issues/155#issuecomment-26546077

**Comment by snej** [comment]
We've never used TCP keepalive for this purpose; both because CouchDB already had an application-level equivalent in the `_changes` feed's heartbeat, and because the necessary `setsockopt` call may not be available on all platforms. For instance, the Mac/iOS implementation uses NSURLSession, which doesn't expose the underlying socket nor provide a keepAlive parameter.

But you're right that we should have a period heartbeat that sends data over the socket periodically, as in the REST changes feed.

**Comment by tleyden** [comment]
Ok thanks, I'm closing this and opening related Sync Gateway and LiteCore tickets:

- https://github.com/couchbase/sync_gateway/issues/3216 
- https://github.com/couchbase/couchbase-lite-core/issues/356
